import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to 💰 Ecommerce Storefront 💎 <a href="https://nextjs.org">Next.js ⚡</a>
        </h1>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://aws.oceansoft.io?utm_source=serverless&utm_medium=ecommerce-storefront&utm_campaign=serverless"
          target="_blank"
          rel="noopener noreferrer"
        >
          💎 A Next.js Storefront for the Shopify-like Digital Commerce Platform ⚡{' '}
          <span className={styles.logo}>
            <Image src="/logo.svg" alt="OceanSoft Logo" width={16} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
